services:
  - type: web
    name: eduweb-backend
    runtime: docker
    env: java
    build:
      dockerfile: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    database:
      postgresql: edudb_cwq0